# .github/workflows/workflow-b.yml
name: Workflow B

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
    - name: Run job 1
      run: echo "Running Build in CI Workflow"
      
  ci-test:
    runs-on: ubuntu-latest
    steps:
    - name: Run job 2
      run: echo "Running Deploy in CI Workflow"
