# .github/workflows/workflow-b.yml
name: ci-Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Select what AML service to run
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      api: ${{ steps.filter.outputs.api }}
      auth: ${{ steps.filter.outputs.auth }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          api:
            - 'api/**'
          auth:
            - 'auth/**'

  auth-ci:
    needs: changes
    if: ${{ needs.changes.outputs.auth == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Run job 1
      run: echo "Running Auth in CI job"
      
  api-ci:
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Run job 2
      run: echo "Running API in CI job"
