name: Deploy to Dev and Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Building project
        run: echo "The build succeeded"
    
  deploy:
    name: Deploy to Dev and Prod
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev]  # Define your environments here

    environment:
      name: ${{ matrix.environment }}  # Use the matrix to name the environment
      url: ${{ vars.URL }}

    steps:
      - name: Manual approval
        #if: matrix.environment == 'prod'
        uses: trstringer/manual-approval@v1
        with:
          approvers: NgomSysOps
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from Dev"
          issue-body: "Please approve or deny the deployment to prod"
          exclude-workflow-initiator-as-approver: false
      
      - name: Display Environment and Variables
        run: |
          echo "ENVIRONMENT: ${{ matrix.environment }}"
          echo "MY_VAR: ${{ vars.MY_VAR }}"
          echo "URL: ${{ vars.URL }}"

