name: Deploy to Dev and Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Building project
        run: echo "build succeeded"
    
  deploy:
    name: Deploy to Dev and Prod
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]  # Define your environments here

    environment:
      name: ${{ matrix.environment }}  # Use the matrix to name the environment
      url: ${{ vars.URL }}

    steps:
      
      - name: Display Environment and Variables
        run: |
          echo "ENVIRONMENT: ${{ matrix.environment }}"
          echo "MY_VAR: ${{ vars.MY_VAR }}"
          echo "URL: ${{ vars.URL }}"

