name: Deploy to Dev and Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Dev and Prod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]  # Define your environments here

    environment:
      name: ${{ matrix.environment }}  # Use the matrix to name the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Display Environment and Variables
        run: |
          echo "ENVIRONMENT: ${{ matrix.environment }}"
          echo "MY_VAR: ${{ env.MY_VAR }}"
          echo "URL: ${{ env.URL }}"

