name: Deploying app
#permissions: write-all
permissions:
  issues: write  # Grant write access to issues
  contents: read # Read-only access to the repository content (optional)
  
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy to Dev and Prod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]  # Define your environments here

    environment:
      name: ${{ matrix.environment }}  # Use the matrix to name the environment
      url: ${{ vars.URL }}

    steps:
      - name: Manual approval
        id: approval
        if: matrix.environment == 'prod'
        uses: trstringer/manual-approval@v1
        timeout-minutes: 1
        with:
          secret: ${{ github.TOKEN }}
          approvers: NgomSysOps
          minimum-approvals: 1
          issue-title: "Deploying app to prod"
          issue-body: "Please approve or deny the deployment to prod environment"
          exclude-workflow-initiator-as-approver: false
          
      - name: Approval Timeout or Cancellation
        if: always() && steps.approval.outcome == 'cancelled'
        run: echo "Manual approval step was cancelled or timed out. The deployment has been stopped."

      - name: Approval Timeout or success
        if: always() && steps.approval.outcome == 'success'
        run: echo "Manual approval is success"
        
      - name: Display Environment and Variables
        run: |
          echo "ENVIRONMENT: ${{ matrix.environment }}"
          echo "MY_VAR: ${{ vars.MY_VAR }}"
          echo "URL: ${{ vars.URL }}"
          
