# .github/workflows/workflow-a.yml
name: Workflow A

on:
  workflow_run:
    workflows: ["Workflow B"]   # This matches the name of Workflow B
    types:
      - completed   # Listen for the completion of Workflow B

jobs:
  run-after-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if Workflow B succeeded
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run some job
      run: echo "Running Workflow A because Workflow B succeeded!"
