# .github/workflows/workflow-b.yml
name: Workflow B

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run job 1
      run: echo "Running Build in Workflow B"
      
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run job 2
      run: echo "Running Deploy in Workflow B"
